### PR TITLE
update go.mod to golang 1.18

### PR DESCRIPTION
**Pull request by slimm609**
update go.mod to golang 1.18 to match version in releaser

### CODE REVIEW

**Review by martin-helmich — APPROVED** [review]

**Review by martin-helmich — DISMISSED** [review]

**Comment by slimm609** [comment]
updated kind and helm since both were old as well.  Kind was still deploying 1.18

**Comment by slimm609** [comment]
@martin-helmich This should fix the issue with the failing tests

**Comment by slimm609** [comment]
@martin-helmich any update on this?

**Comment by martin-helmich** [comment]
Oh, apologies. This looks good to me -- I'm just trying to figure out why the pipeline was not executed.

**Review by martin-helmich — APPROVED** [review]

**Pull request merged**
