### PR TITLE
Add support for enabling/disabling the replication of object types

### PR DESCRIPTION
**Pull request by aljoshare**
This PR adds the support for enabling or disabling the replication of object types and strengthens the principle of least privilege. For example, you can now disable the replication of roles, role bindings or service accounts if thats not needed for your use case.

Fixes https://github.com/mittwald/kubernetes-replicator/issues/284

### CODE REVIEW

**Comment by aljoshare** [comment]
@martin-helmich For now, I added the flags as examples to the args in the helm values. I could also introduce separate values and toggle also the RBAC (as you wrote in the issue). Should I do that or leave it like this? 😊

**Review by martin-helmich — DISMISSED** [review]
Hey @aljoshare! Thanks for the contribution! 👍 

> I could also introduce separate values and toggle also the RBAC (as you wrote in the issue). Should I do that or leave it like this? 😊

I think for a least-privilege implementation, it would absolutely make sense to also tailor the RBAC roles on the desired replication targets. We can leave this PR as-is, and add that in a follow-up PR (in which case I'd be happy merging this), or adjust this PR -- whatever you prefer. 🙂

**Comment by aljoshare** [comment]
@martin-helmich I added a separate config for the toggles, added them directly to the deployment and refactored the RBAC a little to make it more readable with flow control. 

There is one thing which is maybe not backward compatible: If someone copied the `args: []` instead of just relying on the default value, it would break now. Do you think we should handle this case by adding more complexity or leave it like this because it's not a good idea to copy defaults anyway?

**Comment by aljoshare** [comment]
@martin-helmich Ping 😇

**Review by martin-helmich — APPROVED** [review]
Agh, apologies. 😱🙏   Looks good to me now. 👍

**Comment by martin-helmich** [comment]
> If someone copied the args: [] instead of just relying on the default value, it would break now. Do you think we should handle this case by adding more complexity or leave it like this because it's not a good idea to copy defaults anyway?

I'm not sure if this is actually breaking; IIRC, `with` should not evaluate to true with an empty slice. In any case, I think the probability that a user would have explicitly overridden `args: []` is slim. I'll keep an ear open if any feedback comes in on this.

**Pull request merged**
