### PR TITLE
Helm: initial version of helm chart.

### PR DESCRIPTION
**Pull request by desaintmartin**
Would require some README in order to be really helpful, most notably about RBAC being required by default.

### CODE REVIEW

**Comment by desaintmartin** [comment]
Let's wait a bit before merging, my Release keeps crashing.

**Comment by desaintmartin** [comment]
And I can confirm this works well. :)

**Comment by botzill** [comment]
OK, I was just looking for this :). Can we review and merge this?

**Comment by desaintmartin** [comment]
Sure!
I have currently no time to write proper README but maybe next week.
Adding tests might be interesting as well, like it is done in https://github.com/helm/charts
For your informations, https://github.com/helm/charts is in the process of being decentralized, so it may not be worth it to try to add this chart there but instead see how to publish it in the new hub : https://hub.helm.sh/

**Comment by martin-helmich** [comment]
:+1: Thanks for the PR; I've merged this for now and added a short section to the README.

**Comment by botzill** [comment]
Hi. Thx, any chance to publish this on some public helm repo ?

**Comment by desaintmartin** [comment]
There are two ways:

- charts.git: if someone wants to push it to charts.git as a stable chart, feel free to do it and add us as OWNERS.
I suggest trying to keep the two in syncs, remember that charts.git will disappear within a few months.
- github pages

What would you prefer?

**Comment by botzill** [comment]
You mean https://github.com/helm/charts will disappear? 

github pages is OK for me, important to easily automate the install. 

Thx!

**Comment by desaintmartin** [comment]
Let me write a PR for this in charts.git for now, and keep the two synchronized.

**Comment by martin-helmich** [comment]
>Let me write a PR for this in charts.git for now, and keep the two synchronized.
>I would need the email for the volunteers to maintain this chart upstream.

Just noticed your PR in the helm/charts repo! Thanks for all the work! :+1:
I've left some review comments (including the requested email address) there.

**Comment by martin-helmich** [comment]
Just a quick thought @desaintmartin: Does it make sense to maintain the Helm chart in both repos? I'd lean towards abandoning the chart in this repo when it's also available in charts.git. What do you think?

**Pull request merged**
